sudo: false

branches:
  only:
    - pre-build

language: node_js
node_js:
  - 10

os:
  - osx
  - linux
  - windows
osx_image: xcode9.2

services: docker

script:
  - >
    PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')
  - echo "Building archives for $PACKAGE_VERSION"
  - mkdir -p ./target/
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export ARCHIVE_PLATFORM=linux; build-resources/linux/build.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export ARCHIVE_PLATFORM=darwin; npm install; cp ./build/Release/re2.node ./target/; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export ARCHIVE_PLATFORM=windows; npm install; cp ./build/Release/re2.node ./target/; fi
  - mkdir -p ./archives/
  - tar czvf "./archives/$PACKAGE_VERSION-$ARCHIVE_PLATFORM.tar.gz" ./target/re2.node

deploy:
  provider: s3
  access_key_id: "AKIAZXGMCLOUG6PFVGEB"
  secret_access_key:
    secure: "n7Xc05Q9nC3sltpeaP9xB6gzXyZWXHHMhWuTuPuNnflU+9c/BxOauf2XCRUYvt6cADQH3ihGgCZfJ11XyXowW9ycbmPbPMnhVrYE6UNCPTnqyYq397QzPFb90XJ+zlECdlbE6GrSzlU9lVE3KQdEsvVIiB+eAcgPqSBWLVP3solX1Uo00khHeMjtoGD/OAye2j9E4724Vz/dr8Ja49GOAu6XL62shdtvXIyrmw7YjbUhgUhTDmScOMs94f5SGj6JatxhyaDtHiVd8Lo6olZa5vMaPyxuZEqJEhsZsCfdX+7KWpuSBFEhbzQwVbwIy/D7E6u4plHSPD0nIAcaBpG1WQ6iBRUKOZ0mxFgYmVlNfUFmhu5bHMIxsJX6t8IJZgFSJu7NrIEjzOGwFGTqjOiZ3Ekucln+jXGzV+ibFzbIUWp0XLZ8JktHmwQTGeDncdoA0ESYVefZMuJEaC3no9V6La2euZG+9N6v19f2es+XKUv9pBWdsj+RmjmnftBSeQL/dHXS3xYd1Lt/a56ZQD3HrnRIMumD4KFVFcjxDHyi1fBRTjGa5J/UZ8aWVcam+hv+ZhTTJJ7lftx7Y+jNdK+/yDcAkxlofJcZ2dT7LT7tjsuGig1wB8/YLmlE88QisCDfq8tofqd4tuNYWAyM915k21kP6V+/gXUSZeLXiyRUe2A="
  bucket: "kbn-test-native-modules"
  local_dir: ./archives/
  upload_dir: re2
  acl: public_read
  skip_cleanup: true
  edge: true
