sudo: false

branches:
  only:
    - master

language: node_js
node_js:
  - 10

services: docker

install:
  - docker pull kobelb/build-node-re2:alpha-2
  - sudo chown travis:travis $TRAVIS_BUILD_DIR
  - echo "test" > "$TRAVIS_BUILD_DIR"/foo.txt
  - cat foo.txt
  - docker run --rm --mount type=bind,source="$TRAVIS_BUILD_DIR",destination=/opt/app-root/src/node-re2 kobelb/build-node-re2:alpha-2 build-resources/linux/build.sh

