sudo: false

branches:
  only:
    - master

language: node_js
node_js:
  - 10

services: docker

install:
  - docker pull kobelb/build-node-re2:alpha-1
  - sudo chown travis:travis $TRAVIS_BUILD_DIR
  - docker run --rm -v "$TRAVIS_BUILD_DIR":/opt/app-root/src/node-re2 kobelb/build-node-re2:alpha-1 "npm install"

