sudo: false

branches:
  only:
    - master

language: node_js
node_js:
  - 10

services: docker

before_install:
  - openssl aes-256-cbc -K $encrypted_3bd977adfd95_key -iv $encrypted_3bd977adfd95_iv -in .gcs-secret.json.enc -out .gcs-secret.json -d

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ARCHIVE_PLATFORM=linux; build-resources/linux/build.sh; fi
  - mkdir -p ./archives/
  - tar czvf "./archives/$PACKAGE_VERSION-$ARCHIVE_PLATFORM.tar.gz" ./target/re2.node
script:
  - echo "skipping tests"

deploy:
  provider: gcs
  key_file: .gcs-secret.json
  bucket: "native_modules"
  local_dir: ./archives/
  upload_dir: re2
  acl: public-read
  skip_cleanup: true
  edge: true
