sudo: false

branches:
  only:
    - master

language: node_js

services: docker

before_install:
  - docker pull kobelb/build-node-re2:alpha-1

install:
  - docker run --rm -v "$TRAVIS_BUILD_DIR":/opt/app-root/src/node-re2 kobelb/build-node-re2:alpha-1 yarn
